CREATE TABLE [dbo].[USER_CLAIM_TAB]
(
	[UserClaimId] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [UserId] BIGINT NOT NULL, 
    [ClaimType] VARCHAR(50) NOT NULL, 
    [ClaimValue] VARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_USER_CLAIM_TAB_USER_TAB] FOREIGN KEY ([UserId]) REFERENCES [dbo].[USER_TAB]([UserId])
)
